
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Konfigurationen
homeassistant:
  packages: !include_dir_named sensor_configs

# nur krasse Sachen loggen
#logger:
#  default: info
#  logs:
#    homeassistant.components.modbus: fatal
#    pymodbus.logging: fatal
